apiVersion: v1
kind: Pod
metadata:
  name: voting-app-pod
  labels:
    name: voting-app-pod
    app: voting-app
spec:
  containers:
    - name: voting-app-container
      image: kodekloud/examplevotingapp_vote:v1
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: 256Mi
          cpu: "1"
        requests:
          memory: 128Mi
          cpu: "0.2"