# We have updated the /home/bob/playbooks/practice.yaml file with a dictionary named employee. 
# We would like to record information about multiple employees. Convert the dictionary named employee to an array named employees.

employees:
  - name: john
    gender: male
    age: 24
  - name: sarah
    gender: female
    age: 28

# We have updated the /home/bob/playbooks/practice.yaml file to add some more details. 
# Now add the pay information. Remember, while address is a dictionary, payslips is an array of month and amount.
employee_details:
  name: john
  gender: male
  age: 24
  address:
    city: edison
    state: new jersey
    country: united states
  payslips:
    - month: june
      amount: 1400
    - month: july
      amount: 2400
    - month: august
      amount: 3400